apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  namespace: dataviz-ns
spec:
  type: NodePort
  selector:
    component: app-server
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
    
  


