apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deploy
  namespace: dataviz-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        component: app-server
    spec:
      initContainers:
      - name: setup-app-server
        image: busybox
        command: ["sh", "-c", "echo Preparing app server... && sleep 10"]
      containers:
      - name: main-app-server
        image: mongo:5.0
        env:
        - name: RUN_MODE
          valueFrom:
            configMapKeyRef:
              name: app-server-config
              key: RUN_MODE
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: app-server-secret
              key: DATABASE_USER
        - name: DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: app-server-secret
              key: DATABASE_PASS
        volumeMounts:
        - name: logs-shared
          mountPath: /var/log/shared
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      - name: log-sidecar
        image: busybox
        command: ["sh", "-c", "while true; do date >> /var/log/shared/app.log; sleep 5; done"]
        volumeMounts:
        - name: logs-shared
          mountPath: /var/log/shared
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      volumes:
      - name: logs-shared
        emptyDir: {}
