apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dataviz-ns
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
    
  


