apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dataviz-ns
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 3000
    nodePort: 30173
