apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dataviz-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: frontend-pvc
        persistentVolumeClaim:
          claimName: mongodb-pvc
      initContainers:
      - name: init-frontend
        image: busybox
        command: ["sh", "-c", "echo '<h1>Welcome to the Frontend</h1>' > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: frontend-pvc
          mountPath: /usr/share/nginx/html
      containers:
      - name: frontend
        image: ismailza/mern-stack-app-frontend:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: frontend-pvc
          mountPath: /usr/share/nginx/html
